name: CI

# Run only when commits lands on main (and for PRs targetting main)

# Trigger: When do we want this to run?

# We want it to run on every push to the "main" branch

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  lint:
    name: Run Static Linting 
    runs-on: ubuntu-latest
    
    steps:

      # 1. Checkout your repository (downloads all code/folders)
      - name: checkout repository
        uses: actions/checkout@v4

      # 2. Setup Python (required to install flake8/black)
      - name: set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

          
      # 3. Install Linting Tools ONLY (no requirements.txt needed)
      - name: Install linting tools 
        run: |
          python -m pip install --upgrade pip
          pip install black==25.11.0 flake8


     # 4. Run Black (checks formatting, does not modify files) & 
     # 5. Run Flake8 (Static error + style check) 
     # This will recursively check all .py files everywhere.


      - name: Run Black and Flake8
        run: |
          black .
          flake8 .





      
